name: Code Climate Analysis
run-name: Analisis del código
on:
  push:
    branches:
      - main

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Code Climate Test Reporter
        run: |
          curl -L https://github.com/codeclimate/test-reporter/releases/latest/download/test-reporter-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          
      - name: Run Code Climate Analysis
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_TOKEN }}
        run: |
          ./cc-test-reporter before-build
          # Aquí deberías agregar el comando para ejecutar tus pruebas
          ./cc-test-reporter after-build --exit-code $?
