name: Matriz de ejecucion Node

run-name: Ejecucion de Node

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12, 14, 16]
    steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
        
        - name: Install dependencies
          run: npm install

        - name: Run tests
          run: npm test
      